### ISSUE TITLE
Document improvements

### ISSUE THREAD

**Issue by Dynom** [jirsbek/ssh-keys-in-macos-keychain#2]
Hi,

If you install a more recent SSH version via (e.g.) brew one might get the:

``` sh
$ ssh-add -K
ssh-add: illegal option -- K
```

Pass the full path to ssh-add (`/usr/bin/ssh-add`) to work around this problem.

**Comment by mxstbr** [comment]
Hahaha that works, what on earth!

**Comment by jirsbek** [comment]
@Dynom Thank you for noticing that, readme has been updated.

**Comment by goforgold** [comment]
Didn't work with specifying full path either

```
/usr/bin/ssh-add -K /home/path/to/id_rsa
ssh-add: illegal option -- K
usage: ssh-add [options] [file ...]
Options:
  -l          List fingerprints of all identities.
  -L          List public key parameters of all identities.
  -d          Delete identity.
  -D          Delete all identities.
  -x          Lock agent.
  -X          Unlock agent.
  -t life     Set lifetime (in seconds) when adding identities.
  -c          Require confirmation to sign using identities
  -s pkcs11   Add keys from PKCS#11 provider.
  -e pkcs11   Remove keys provided by PKCS#11 provider.
  -n          Add keys in NSS key.
  -T          Name NSS key explicitly.
```

Note: I am on CentOS 6.X

**Comment by jirsbek** [comment]
Unfortunately I'm not able to reproduce the problem on the CentOS. This repository is related to macOS only.

**Comment by sojungko** [comment]
@goforgold Try with lowercase `-k`. That worked for me.

**Comment by goforgold** [comment]
thanks @sojungko, worked with lowecase. Silly me!

**Comment by goofiw** [comment]
lowercase -k doesn't complain, but it also doesn't persist across sessions.  (I'm running in this issue on a digital ocean droplet running ubuntu 16.04)
