### ISSUE TITLE
ssh-add -K and -A throw illegal option

### ISSUE THREAD

**Issue by mxstbr** [jirsbek/ssh-keys-in-macos-keychain#3]
I can neither run `ssh-add -K` nor `-A`, both throw "illegal option".

<img width="484" alt="screen shot 2016-10-18 at 20 37 51" src="https://cloud.githubusercontent.com/assets/7525670/19491359/f1903fee-9572-11e6-9113-b114114007a1.png">

<img width="243" alt="screen shot 2016-10-18 at 20 39 49" src="https://cloud.githubusercontent.com/assets/7525670/19491387/09615d24-9573-11e6-98d4-b6afd4459fbb.png">

**Comment by danekszy** [comment]
`ssh-add -A` doesn't need any file path in this case.
Have you tried the `-K` with absolute path?

**Comment by mxstbr** [comment]
As far as I know `~/.ssh/id_rsa` _is_ an absolute path, but I tried `ssh-add -K /Users/username/.ssh/id_rsa` anyway and it threw the same error. `ssh-add` just doesn't recognize the option.

**Comment by benpbolton** [comment]
hey @mxstbr , unsure if you have a custom (newer?) ssh installed, but you might check out issue #2  or `which ssh-add` to determine pathing...

**Comment by danekszy** [comment]
FYI (we've commented this on twitter):
I still have this option available in help (10.12), while @mxstbr doesn't (10.12.1 - beta)...

**Comment by mxstbr** [comment]
Yess, #2 totally fixed it! What is this sorcery!

**Comment by walkerwzy** [comment]
sorry but hi... i like your terminal theme, can you tell me the name?
