### ISSUE TITLE
Document changes in 10.12.2?

### ISSUE THREAD

**Issue by danielcompton** [jirsbek/ssh-keys-in-macos-keychain#6]
It looks like from http://testequals.com/2016/09/09/macos-sierra-10-12-ssh-keys/ Update 2, that this is now all that is needed to add keys back to the Keychain:

```
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/[your-private-ssh-key-name]
``

**Comment by marknorgren** [comment]
Apple has posted a Tech Note now:

https://developer.apple.com/library/content/technotes/TN2449/_index.html#//apple_ref/doc/uid/DTS40017589

**Comment by jirsbek** [comment]
Thank you for the info, it looks very promising. I'll test it and update the document.
