### ISSUE TITLE
I'd suggest mentioning GIT_SSH

### ISSUE THREAD

**Issue by xpe** [jirsbek/ssh-keys-in-macos-keychain#7]
If you are seeing the "Bad configuration option: usekeychain" error during a `git` command, it may be because Git isn't running the Apple-installed version of SSH. To ensure that you know which version of `ssh` is called from `git`, set an environment variable:

```
GIT_SSH="/usr/bin/ssh"
```

More generally, any wrapper of SSH could cause this kind of error. So I'd suggest checking which SSH binary is actually called.

**Comment by jirsbek** [comment]
I would like to aim this repository to SSH keys and keychain only without relation to other usage. Anyway feel free to PR, if it's common problem.
