### ISSUE TITLE
Multiple identities in .ssh/config results in Too many authentication failures for root

### ISSUE THREAD

**Issue by raarts** [jirsbek/ssh-keys-in-macos-keychain#8]
So I'd recommend adding a note, that in case you have more than 3 identities, you'll need to use solution number 2.

**Comment by whizkid79** [comment]
that's not the case for me. works with 8 identities (for different accounts for sure).

**Comment by raarts** [comment]
After more digging, I found that one of my keys was DSA, which is deprecated by openssh 7, and it was on the server I tried logging in to.
I replaced the public key on the server with an RSA one, and the error went away.

Sorry about this.
