### ISSUE TITLE
Simpler config suggestion?

### ISSUE THREAD

**Issue by raarts** [jirsbek/ssh-keys-in-macos-keychain#9]
Can't the same effect be accomplished by just specifying this at the top of the config file:

    AddKeysToAgent=yes
    UseKeychain=yes

Seems to be working for me, even though I haven't rebooted yet.

**Comment by jirsbek** [comment]
Can you please provide source of this information?

**Comment by raarts** [comment]
I got it from `man 5 ssh_config`.

**Comment by benpbolton** [comment]
`UseKeychain` feels magic until you forward your ssh-agent (eg. via `ssh -A`) to a box that doesn't support MacOS's custom implementation... and without an ssh-add -A on every boot, you'll be sad after you restart.

Anyhow, the current readme includes this info
